# Social
title: Cactu
description: >
  Cactu is a SASS framework created to help any developer to create web pages
  very quickly and an easy way
keywords: cactu,css framework,sass framework
author: Giovanni Mendoza
email: mendozagioo@gmail.com
twitter_username: mendozagioo
github_username:  mendozagioo

# Server
baseurl: ""
url: "https://cactu.io"

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-redirect-from
  - jekyll-toc

exclude:
  - .git/
  - node_modules/
  - scss/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md

toc:
  min_level: 2
  max_level: 3